# -*- mode: ruby -*-
# vi: set ft=ruby :
# Every Vagrant development environment requires a box. You can search for
# boxes at https://atlas.hashicorp.com/search.


BOX_IMAGE = "bento/ubuntu-16.04"
BOX_IMAGE_MASTER = "centos/7"
NODE_COUNT = 3

Vagrant.configure("2") do |config|

        #Vagrant -  with master
        config.vm.define "master" do |subconfig|
                 subconfig.vm.box = BOX_IMAGE_MASTER
                 subconfig.vm.hostname = "master"
                 subconfig.vm.network :private_network, ip: "10.0.0.10"
        end

        #Vagrant - 10.0.0.11 - node1.intranet.local   ||  10.0.0.12 - node2.intranet.local
        NODE_COUNT.times do |i|
            node_id = "node#{i}"
            config.vm.define node_id do |node|
                    node.vm.box = BOX_IMAGE
                    node.vm.hostname = "#{node_id}.intranet.local"
                    node.vm.network :private_network, ip: "10.0.0.#{i + 10}"
          end
        end
        config.vm.provision "shell", inline: <<-SHELL
                sudo apt-get update
                sudo apt-get install -y avahi-daemon libnss-mdns
                sudo apt-get install iputils-ping
                sudo apt-get install -y unzip openjdk-8-jre-headless                
        SHELL
end
