# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|


        config.vm.define "master" do |subconfig|
                 subconfig.vm.box = "centos/7"
                 subconfig.vm.hostname = 'master'
                 subconfig.vm.network :private_network, ip: "10.0.0.10"

                subconfig.vm.provision "shell", inline: <<-SHELL
                        sudo yum -y install epel-release
                        sudo yum -y install python-pip
                        sudo pip install --upgrade pip
                        sudo pip install six==1.4
                SHELL

        end


        config.vm.define "node01" do |subconfig|
                 subconfig.vm.box = "centos/7"
                 subconfig.vm.hostname = 'node01'
                 subconfig.vm.network :private_network, ip: "10.0.0.11"

                subconfig.vm.provision "shell", inline: <<-SHELL
                        sudo yum -y install epel-release
                        sudo yum -y install java
                SHELL

        end
end
